### PR TITLE
Shallow cloning for better performance

### PR DESCRIPTION
**Pull request by sztomi**
* `--depth 1` avoids cloning a bunch of object that are not needed just for building, so it's much faster
  * `--branch xxx` clones the selected branch or tag right away

### CODE REVIEW

**Comment by sourcedelica** [comment]
That's great, I didn't know `--branch` worked with tags too.   Let me check it out and then merge it.

**Comment by sourcedelica** [comment]
I wonder if it's possible to do something similar for submodules.  Those are slow too.

**Comment by sztomi** [comment]
Good idea, and it seems that it's possible: https://github.com/git/git/blob/726cc2ba12c4573ab2e623077479c51019e1f3cd/Documentation/RelNotes/2.9.0.txt#L116

**Comment by sourcedelica** [comment]
I tried to use `git clone --depth 1 --shallow-submodules --recursive` and also `git clone --depth 1; git submodule update --init --depth 5`.  Both of them gave me the error:

    error: no such remote ref c880e42ba1c8032d4cdde2aba0541d8a9d9fa2e9. 
    Fetched in submodule path 'third_party/boringssl', but it did not contain 
    c880e42ba1c8032d4cdde2aba0541d8a9d9fa2e9. Direct fetching of that commit failed.

Based on the answers to http://stackoverflow.com/questions/2144406/git-shallow-submodules it seems that `--shallow-submodules` is kindof finicky.  I've put in a TODO to revisit.  If you figure out a way to get it to work reliably let me know, it would be nice to have.

**Comment by sztomi** [comment]
Another approach might be downloading the submodules as tarballs (many projects provide one or they could just be uploaded as release tarballs to this repository).

**Comment by sourcedelica** [comment]
True - though it would need to be balanced against the complexity.  We'd need to keep track of the  versions of all the sub-projects as gRPC evolves.  Currently `git submodule update` is slow enough that a simple solution would be nice to have, but fast enough that it's not crying out for a more complex solution.

**Comment by sztomi** [comment]
@sourcedelica just FYI I came across another faster way of downloading specific commits, although it is github-specific: one can request the URL https://github.com/<user>/<repo>/archive/<commit hash>.zip and get it super-fast. For example: https://github.com/rpclib/rpclib/archive/708a75ce488dccc795cfcda310c1ab5141491217.zip

**Comment by sourcedelica** [comment]
Cool!  That's a good one to have the back pocket.

**Pull request merged**
